/*
 * This source file was generated by the Gradle 'init' task
 */
package org.attendance;

public class AppOld {
    public String getGreeting() {
        return "Hello World!";
    }

//    public static void main(String[] args) {
//        System.out.println(new org.attendance.AppOld().getGreeting());
//    }
}
